@OOP_3_HostAddress = http://localhost:5191

GET {{OOP_3_HostAddress}}/api/shops
Accept: application/json

###

POST {{OOP_3_HostAddress}}/api/shops
Content-Type: application/json

{
  "code": "1",
  "name": "Дикси",
  "address": "Саблинская, 13"
}

###

GET {{OOP_3_HostAddress}}/api/products
Accept: application/json

###

POST {{OOP_3_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "Вафли"
}

###

POST {{OOP_3_HostAddress}}/api/stocks
Content-Type: application/json

{
  "shopCode": "1",
  "productName": "Сникерс",
  "quantity": 50,
  "price": 40
}

###

GET {{OOP_3_HostAddress}}/api/stocks/cheapest?productName=Chocolate%20Bar
Accept: application/json

###

POST {{OOP_3_HostAddress}}/api/purchases
Content-Type: application/json

{
  "shopCode": "1",
  "items": [
    { "productName": "Сникерс", "quantity": 3 }
  ]
}

###
